
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 20 22:32:52 CET 2017
//----------------------------------------------------

package mini_c;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 30;
  public static final int SIZEOF = 20;
  public static final int AND = 7;
  public static final int LT = 12;
  public static final int NE = 11;
  public static final int ELSE = 5;
  public static final int IDENT = 2;
  public static final int IFTHEN = 33;
  public static final int PLUS = 28;
  public static final int STRUCT = 17;
  public static final int OR = 8;
  public static final int EQUAL = 26;
  public static final int LP = 21;
  public static final int WHILE = 19;
  public static final int RP = 22;
  public static final int NOT = 9;
  public static final int RETURN = 6;
  public static final int IF = 4;
  public static final int GT = 14;
  public static final int LE = 13;
  public static final int SCOLON = 27;
  public static final int LC = 23;
  public static final int RC = 24;
  public static final int TYPE = 16;
  public static final int COMMA = 25;
  public static final int CST = 3;
  public static final int EOF = 0;
  public static final int DIV = 31;
  public static final int MINUS = 29;
  public static final int GE = 15;
  public static final int ARROW = 18;
  public static final int error = 1;
  public static final int EQ = 10;
  public static final int UMINUS = 32;
}

