
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package mini_c;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 18;
  public static final int SIZEOF = 25;
  public static final int AND = 9;
  public static final int LT = 12;
  public static final int NE = 11;
  public static final int ELSE = 5;
  public static final int IDENT = 2;
  public static final int IFTHEN = 33;
  public static final int STRUCT = 22;
  public static final int PLUS = 16;
  public static final int OR = 8;
  public static final int LP = 26;
  public static final int EQUAL = 7;
  public static final int WHILE = 24;
  public static final int RP = 27;
  public static final int NOT = 20;
  public static final int RETURN = 6;
  public static final int IF = 4;
  public static final int GT = 14;
  public static final int LE = 13;
  public static final int SCOLON = 31;
  public static final int LC = 28;
  public static final int RC = 29;
  public static final int TYPE = 21;
  public static final int COMMA = 30;
  public static final int CST = 3;
  public static final int EOF = 0;
  public static final int DIV = 19;
  public static final int MINUS = 17;
  public static final int GE = 15;
  public static final int ARROW = 23;
  public static final int error = 1;
  public static final int EQ = 10;
  public static final int UMINUS = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENT",
  "CST",
  "IF",
  "ELSE",
  "RETURN",
  "EQUAL",
  "OR",
  "AND",
  "EQ",
  "NE",
  "LT",
  "LE",
  "GT",
  "GE",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "NOT",
  "TYPE",
  "STRUCT",
  "ARROW",
  "WHILE",
  "SIZEOF",
  "LP",
  "RP",
  "LC",
  "RC",
  "COMMA",
  "SCOLON",
  "UMINUS",
  "IFTHEN"
  };
}

